# Generated by Django 4.1.3 on 2022-11-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_organisme_projet_remove_phase_livrable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livrable',
            name='libelle',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
